### ISSUE TITLE
Error in function stitch_images

### ISSUE THREAD

**Issue by Abdul-Mukit** [phsamuel/findhomographyhw#1]
`def stitch_images(img1,img2,h1):

    s=np.dot(h,np.array([[*img1.shape[1::-1],1],[1,1,1],[img1.shape[1],1,1],[1,img1.shape[0],1]]).transpose())`

s is calculated using h, not the h1 provided in the function definition.

**Comment by phsamuel** [comment]
It was fixed. thanks for catching that.
